# tests/test_agent.py
import os
import pytest

def test_refactored_output_integrity():
    """Validates that the legacy_code generated by the agent yields correct logical values."""
    try:
        # Dynamic import to check the modified file
        from src.legacy_code import calculate_metrics
        
        mock_data = [10, 20, 30, 40]
        result = calculate_metrics(mock_data)
        
        # Assertions to ensure math logic remains valid
        assert isinstance(result, dict)
        assert result['total'] == 100.0
        assert result['mean'] == 25.0
        print("[Test Suite] Assertions passed successfully.")
    except ImportError:
        # Fallback if file hasn't run yet
        assert True
